### ISSUE TITLE
Help wanted?

### ISSUE THREAD

**Issue by geemus** [lostisland/faraday-excon#9]
Greetings, I'm the primary author and maintainer of excon/excon and I was wandering if you all might like assistance with the adapter?

If so, I hoped we could discuss what you are looking for and what that might look like. The easiest from my perspective might just be if you could grant me permissions on the repo and package, after which point I can update and refine it as I'm able. But I can certainly understand if you'd like to take a more gradual approach to engagement.

I have somewhat limited availability at present, but I definitely think I could make some nice positive changes without a lot of time and effort (bumping dependency versions for instance and looking at some of the low hanging fruit of better integration/support).

In any event, I'd welcome your thoughts and discussion on possible collaboration here. Thanks!

**Comment by iMacTia** [comment]
Hi @geemus and thank you for reaching out!
We are most definitely open to collaborating on the adapter and I'm sure your experience and knowledge of Excon will help a lot!

To give you some historical context (and apologies if you have this already) before v2 Faraday was shipping with a bunch of adapters "out-of-the-box", including the Excon one, that were added over time by either the core team or outside contributors.

As you can imagine, keeping all these up-to-date every time we wanted to introduce a new feature was incredibly complicated and time consuming, so we decided to slowly isolate them into separate gems and the remove the dependency to these gems in the V2 release, effectively making them optional "add-ons".

Now, none of the Faraday maintainers today have much experience with most of these adapters, so we mostly run essential maintenance on them and do our best to review PRs. We do this as a service and to provide continuity, so we're very much open to anyone who would like to help with this.

All this to say there's no need to tiptoe in or worry about our big long-term projects for these adapters because frankly we have nothing like that.

Your suggestion of collaborating on this repository makes perfect sense to me, as this would allow us to contribute with Faraday-specific updates and you (and other Excon maintainers, if they'd like to be added) to contribute updates, improvements in line with the client.

However, we're also open to alternative arrangements if that makes it easier for you:
- Move the repository under the same org/account as Excon
- Move the adapter code into Excon directly (not personally a fan of this, but that's what the Typhoeus team ended up doing)

Please do consider all the above and let me know how to proceed 👍

**Comment by geemus** [comment]
Thanks for the context, I'd guessed something similar, but it always helps to know for sure. I certainly had a similar experience of adapters in the project being fine at first but quickly becoming too much with fog (where it still isn't really totally sorted out, but is probably good enough).

It's good to know that we shouldn't need to tread too carefully, at least for the time being. That makes it sound like we could probably mostly do a handover safely and (hopefully) not block on each other too much.

I would definitely welcome any hints you might have on Faraday-specifics that might be missing and what people use the most or find most valuable to help me prioritize work as I'm able to find the time. Similarly, I imagine between the docs and tests I can hopefully mostly find my way around, but I'd definitely appreciate being able to reach out for advice and review from time to time.

This is a bit tangential, but I've also noticed there are some parallel features between excon and faraday (like middlewares and stubs for instance) and it might be interesting to discuss our approaches at some point. I've thought about trying to rework parts of these and I'd love to learn from your experience. Plus it might be interesting to see if there are any possibilities for sharing code or functionality (ie I think we both have implementations of middlewares that look/sound like they are trying to do more or less the same things).

I hadn't even thought about moving the repository. As you suggest, that might actually be easiest from my end and that would be great if it could reduce any burden on you as well. That being said, we don't necessarily have to start with that as we could always move it later. Do you all have a particular preference? (I would tend to agree that I'd much rather keep it as a distinct repository from excon, regardless of which org it lives in).

Would you also be alright with granting me gem permissions so I can manage releases? I think that could definitely reduce coordination overhead as we move forward.

**Comment by iMacTia** [comment]
Thank you for the thoughtful reply @geemus.
In the short term, I'll grant you admin access to the repository as a collaborator to get things started and give you time to get acquainted, but happy to move it as soon as you want. I really don't mind as to where the project sits, and you can always add me and @olleolleolle as collaborators after the move if you'd like to keep us in the loop whenever you need input from us.

For releases, I can add you as an owner to the gem, but in the meantime you can cut a new release by simple creating a new version on GitHub thanks to [this Action workflow](https://github.com/lostisland/faraday-excon/blob/main/.github/workflows/publish.yml). This is a common strategy we use across faraday repos to allow all collaborators to ship new versions and also ensure the GitHub "releases" and tags are up-to-date 🙂

> This is a bit tangential, but I've also noticed there are some parallel features between excon and faraday (like middlewares and stubs for instance) and it might be interesting to discuss our approaches at some point. [...]

Happy to discuss all these points further. We can do it here in GitHub using discussions, or I'm sure we can meet in a Slack/Discord server 😄 (we have a Slack org for Faraday that only has core team members at the moment, but I think we can use).

**Comment by geemus** [comment]
Sounds good, I was able to accept the invite earlier today so I think I'm good to go there.

Cool, I haven't seen an action setup like that before. I guess one of you has placed your gem credential in the secrets? That's probably fine for now, though if we transfer it I guess we would probably need to do permissions stuff.

Discussions and/or slack/discord sound good eventually, no rush from me.

I'll try to find some time to dig in soonish, thanks again and I'll let you know if I need anything.

Going to close this issue as good for now, thanks again!

**Comment by geemus** [comment]
@iMacTia I finally had a chance this morning to do some review and basic maintenance, so I feel like I have a much better understanding of the scope of things. I don't think I totally grok everything quite yet, but it seems pretty small/narrow, which helps. I feel pretty confident I should be able to at least keep it going, and can dig into the possibility of refining and adding capabilities when I have a bit more time/focus available for it.

With this extra experience/understanding I think I would now be comfortable moving stuff if you'd still like to do that (moving the repo to the excon org and getting rubygems permissions so I'll be able to do pushes). Just let me know if that is still of interest to you and/or if you need anything else to enable that.

**Comment by iMacTia** [comment]
Hey @geemus, that's great news! I'm glad to hear that. Still supportive of the idea of moving the repo under Excon.
If your current admin permissions allow you to do so, then please feel free to proceed.

Otherwise I'll happily help as soon as I recover from coming down with a nasty fever 🤒

**Comment by geemus** [comment]
@iMacTia sorry to hear about the fever, I just went through some of that myself and it was not fun. There is no hurry from my perspective, so please take your time and focus on recovery.

When you are back, I looked and it does appear that with my admin permissions I am able to transfer it, so I'm happy to do that. That being said, I believe that this will break the release action (as it would no longer have access to the rubygem credential secret from the lostisland org). So, in order to ensure there is continuity of the ability to release, I'd like to wait until you have a chance to add me as a releaser on the gem. Once we have that, I can work on migrating the organization and making any other relevant changes. Just let me know if you have questions or different ideas on how to proceed.

Thanks, and I hope you feel better ASAP.

**Comment by iMacTia** [comment]
@geemus thank you for your patience, I've now added you as an owner to the gem.
Once you accept the invite and confirm access, feel free to proceed with the transfer 👍

**Comment by geemus** [comment]
@iMacTia Not a problem, I hope you are feeling better now. I was just able to confirm and I'll proceed with the transfer presently.
